language: node_js
node_js:
- '0.12'
cache:
  directories:
  - node_modules
  - libs
deploy:
  provider: heroku
  api_key:
    secure: JRCk/EFwEAZZJBWUvt8PvCGFmrn9UJ87g1isS1OZfz2I5oT7CRdnI0koS7+66w31J5uzaucT5xBNbN/X/4SKKJ6proOH9BSSAlSok4+xXKQzb1ebQ9dOlQPhEj3BtOCEl5xw77A3kJo4H7dKeKmghtr+sjja89jLk6jrWntnnP+T15iSiL7LU8LsWjmsDNpcDYepu3hKAVLMht1yCskn3+yHX0UhzXaoOt5sTRiheVcXPoDqjUvxt50OjFWsOKe7vToF6mxTQTndZoYS87FYsoXjQDAvF052RL9LdkTZjsjDPOg8ccPogiuQAn0hbCM9KaVtDzGKQdjHN6mX+V70P9gzNrnReVozPIpr0p4T9qPvvfiIxZPhYvjJpzV2QeDNaEuMRjbUrPJNuUoPrOO99t8c1W0stTLAujo277iG38aJjZ+9sMF3TuvjjNmmGAuN52Od4qvWacsMD0QRaaAw0CMWeWN19Lmau//CHtozNCB8hhz2jcgI5hZ6T6hganGdXVVbDui+huEp3ISAdWatHxg37KsJ9ci4tv8tsZkkZWdt/U3yjb9ZjLF7rIekZk5goKWcmegVb8WWbc8GqCDMIYXAzvkYCZUSUi8rlBVplW6fGljx/7vVguTuve6uvxQZAvaJaGbjP8idKF8bF218RTxeJRjDyTg9K5ttaxykfJ8=
  app: safe-basin-4405
  on:
    repo: TRI-COR/tricor-bpa-prototype
