language: node_js
node_js:
- '0.12'
cache:
  directories:
  - node_modules
deploy:
  provider: opsworks
  access_key_id: AKIAJSDKSCPUAFGJPOIA
  secret_access_key:
    secure: fvVZMKS4iJHLRIgwYeGhpU/fi8o12R43lhgYKlR45RpMV7lyJvYCz8KYmwEHsIbEPRRa/nAFcUru5mAF2AC4796Bmjly6tRuhQ2UVdbXtdyodwrgKpJbjsmAZ4kafLJRzog6eLYX/lV1OfOUmBFFVGF91j0djzGkRYDIp3JozQ0KhG/qF+YNlZiM3O2N0h1X1E2fHLHbwpyKSEe5m9yjVF4EPoyMwYzVsqJMXumlHTD7WeI192oKLQeV9nnNbfpMenP3Ta6jI9NrjHQ7PEQsDBzGlNhELX3kHDt6rHPzaRjOcsyQOpcJsOxXVtybLrUHp1O00nUqhXr1UdMCoAKsKgSh3FcqXlL7caCP/xlGwhrayFMcGFS79eUboVnIqEaBQ3sNvYTDEJhnJa9ImGiJKfNy9+EYyq4P6Nv95GyA6H2BaMXBzapNEDTOlMISjz3dURmEntUJIL3CSY8FPf2c2dneEnp+oHf8JCkcsSqV3i1pWoGZsb++Y1q6ALQ4oXg5bSgbCnJGbsdSc3CJBVnt1pm3OS9+5MA1nDswQTNwQrrjHqWgQ4RO2/uSu6rcqnDxkfWOA4roYlNl8jEV5rwbHUIM3yJJV/LGlmXGl52+sLziegtio7szf33BgFtovA8iwfsD0N9fx589lq5lVaSNKOy1QIRPwWpTMcBcB3zmo00=
  app-id: nodejs-app1
  on:
    repo: TRI-COR/tricor-bpa-prototype
